### ISSUE TITLE
Bug with dynamic versioning

### ISSUE THREAD

**Issue by gazpachoking** [carstencodes/pdm-bump#25]
When trying to bump a dynamic version right now, it causes the following traceback:

```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\chase\AppData\Roaming\Python\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 258, in main
    return Core().main(args)
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 185, in main
    f(project, options)
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm_bump\logging.py", line 195, in tracing_function
    return fun(*args, **kwargs)
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm_bump\plugin.py", line 146, in handle
    version: Version = backend.current_version
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm_bump\dynamic.py", line 46, in __get_current_version
    dynamic: DynamicVersionConfig = self.__get_dynamic_version()
  File "C:\Users\chase\AppData\Roaming\pdm\venv\lib\site-packages\pdm_bump\dynamic.py", line 72, in __get_dynamic_version
    ] = __find_dynamic_config(self.__project_root, self.__config)
NameError: name '_DynamicVersionSource__find_dynamic_config' is not defined
```

I think we should probably just switch the private functions to single underscore prefixes, so we don't have to deal with name mangling issues.

**Comment by carstencodes** [comment]
Good idea.

I went a step on and replaced the dataclass with a dead simple python class in #26 

Fix will be part of v0.6.9 about to come in a few minutes.

(One day I will have the time to perform tests)
