### ISSUE TITLE
Error while bumping up version 

### ISSUE THREAD

**Issue by QIvan** [carstencodes/pdm-bump#264]
Hello! Thank you for this project; it's a very useful tool 
but it seems like the last version has a bug. At least today, when I ran the same CI build that worked for ages, it failed with an error: 
>  'NoneType' object has no attribute 'merge'

The full verbose log you may see below:

```
Configuration is set to: 
{'source': 'file', 'path': '__version__.py'}
Found value at 'source' is: file
Searching for 'version.path' in configuration
Configuration is set to: 
{'version': {'source': 'file', 'path': '__version__.py'}, 'write_to': '__version__.py', 'write_template': "__version__ = '{}'", 'package-dir': 'aggr', 'build': {'package-dir': 'aggr', 'includes': ['aggr/', 'dps/']}, 'source': [{'url': 'https://our.nexus', 'verify_ssl': True, 'name': 'pypi'}, {'url': 'https://pypi.org/simple/', 'verify_ssl': True, 'name': 'public-pypi'}], 'resolution': {'respect-source-order': True}, 'scripts': {'_': {'env': {'PYTHONPYCACHEPREFIX': '/tmp/pycache'}}, 'test': 'pytest', 'lint': 'flake8 aggr', 'format': 'python -m black aggr', 'format-check': 'python -m black aggr --diff --check'}, 'dev-dependencies': {'dev': ['flake8', 'black', 'pytz', 'pytest~=6.2', 'pytest-cov~=3.0', 'pytest-mock~=3.6', 'sqlparse~=0.4', 'kusyn']}}
Found configuration section _ConfigKeys.VERSION
Searching for 'path' in configuration
Configuration is set to: 
{'source': 'file', 'path': '__version__.py'}
Found value at 'path' is: __version__.py
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/core/logging.py", line 338, in tracing_function
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/plugin.py", line 193, in handle
    actions.execute(
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/actions/base.py", line 435, in execute
    executor.run(command, context.version, args, dry_run=dry_run)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/core/logging.py", line 338, in tracing_function
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/actions/hook.py", line 247, in run
    version = executor.run(dry_run)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/actions/base.py", line 267, in run
    self.__persister.save_version(next_version)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/core/logging.py", line 338, in tracing_function
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/plugin.py", line 153, in save_version
    self.__backend.current_version = version
  File "/usr/local/lib/python3.10/site-packages/pdm_bump/dynamic.py", line 203, in current_version
    self.__hunk = cast(_DiffData, self.__hunk).merge(hunk)
AttributeError: 'NoneType' object has no attribute 'merge'
make: *** [Makefile:104: docker-bump-version] Error 1
```

**Comment by carstencodes** [comment]
Thanks for bringing up this issue.

The issue could be narrowed down to

https://github.com/carstencodes/pdm-bump/blob/main/src%2Fpdm_bump%2Fdynamic.py#L200-L203

As the erroneous Line is 200 - the Not should be removed.

As it is almost midnight, I will Release a fix tomorrow.

Regards

Carsten
